//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleTbl
    {
        public int Id { get; set; }
        public string FlightNumber { get; set; }
        public string PeriodOfOperation { get; set; }
        public string DaysOfOperation { get; set; }
        public Nullable<System.TimeSpan> DepartureTime { get; set; }
        public string OriginalStation { get; set; }
        public string DestinationStation { get; set; }
        public string Aircraft { get; set; }
    }
}
